### ISSUE TITLE
do not expose global "yue"

### ISSUE THREAD

**Issue by johnd0e** [pigpigyyy/Yuescript#128]
I noticed that using `require("yue")` not only returns the module, but also sets global `yue` variable:
```
> print(yue)
nil
> require"yue"
> print(yue)
table: 0x00698928
```
Is that intended?

**Comment by pigpigyyy** [comment]
Yes, it's intended and done by the Lua C-API from here for Lua version above 5.1
https://github.com/pigpigyyy/Yuescript/blob/b3d021e2bbb08d01961d2a597715faff5e78b715/src/yue.cpp#L47
and here for Lua 5.1
https://github.com/pigpigyyy/Yuescript/blob/b3d021e2bbb08d01961d2a597715faff5e78b715/src/yuescript/yuescript.cpp#L382
So you think it is more of polluting the global env instead of offering convenience?

**Comment by johnd0e** [comment]
> So you think it is more of polluting the global env instead of offering convenience?

Yes, exactly, that is my opinion.

**Comment by pigpigyyy** [comment]
OK, got this issue fixed by lastest commit. After all, it won't cost much effort to manually expose yue as global variable.
