### ISSUE TITLE
Allow to use metatable operators for exporting

### ISSUE THREAD

**Issue by SkyyySi** [pigpigyyy/Yuescript#133]
I think it would be useful if we could use things like this:

```js
export <name> = "My module"
export <call> = (...) -> -- ...
```

In some Lua environments, like Awesome WM, it is common practice to use modules as both namespaces *and* as a constructor.

**Comment by pigpigyyy** [comment]
Added a different syntax to support export metamethod for a module by
```moonscript
export.<name> = "My module"
export.<call> = (...) -> -- ...
```
that compiles to
```lua
local _module_0 = setmetatable({ }, { })
getmetatable(_module_0).__name = "My module"
getmetatable(_module_0).__call = function(...) end
return _module_0
```
Because the statement exporting item with assignment will always leave a local variable. A new syntax for disabling local variable creation when doing export could be a better way to export metamethods (Or we may get messy local variables named like `__call`, `__eq`).
